[tool.poetry]
name = "solbot"
version = "0.1.0"
description = ""
authors = ["Sway Ducky <swayducky@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.9"
anyio = "4.4.0"
attrs = "23.2.0"
base58 = "2.1.1"
black = "24.10.0"
borsh-construct = "0.1.0"
cachetools = "4.2.4"
certifi = "2024.7.4"
charset-normalizer = "3.3.2"
click = "8.1.7"
construct = "2.10.68"
construct-typing = "0.5.6"
grpcio = "1.65.2"
h11 = "0.14.0"
httpcore = "0.16.3"
httpx = "0.23.3"
idna = "3.7"
isort = "5.13.2"
ji = "0.0.4"
jito-py-rpc = "0.1.0"
jito-searcher-client = "0.1.5"
jsonalias = "0.1.1"
mypy-extensions = "1.0.0"
packaging = "24.2"
pathspec = "0.12.1"
platformdirs = "4.3.6"
protobuf = "4.25.4"
python-dotenv = "1.0.1"
requests = "2.32.3"
rfc3986 = "1.5.0"
sniffio = "1.3.1"
solana = "0.34.0"
solc-select = "0.2.1"
solders = "0.21.0"
sumtypes = "0.1a6"
types-cachetools = "4.2.10"
typing-extensions = "4.12.2"
urllib3 = "2.2.2"
websockets = "9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
